version: '3.6'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        container_name: elasticsearch
        environment:
        - cluster.name=docker-cluster
        - node.name=elastic-n1
        - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
        - bootstrap.memory_lock=true
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        volumes:
        - esdata1:/usr/share/elasticsearch/data
        cap_add:
        - ALL
        privileged: true
        ports:
        - 9200:9200
        - 9300:9300
    kibana:
        image: docker.elastic.co/kibana/kibana:6.6.1
        container_name: kibana
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200/
            SERVER_NAME: localhost
        ports:
        - 5601:5601
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        cap_add:
        - ALL
volumes:
    esdata1:
